import NavbarTask from "@/components/NavbarTask";
import "../../globals.css";
import { roboto } from "@/app/styles/font.js";

export const metadata = {
  title: "My page with nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body>
        <NavbarTask />
        {children}
      </body>
    </html>
  );
}
